### PR TITLE
Solo Project Background and gradients

### PR DESCRIPTION
**Pull request by Maclenn77**
Solo project of Microverse. I cloned this [Old Apple Page](https://web.archive.org/web/20140301004610/http://www.apple.com/) using background and gradient properties learned on the previous lesson. There's a navbar with linear-gradient properties, a main with a background. Bottom images are links to Apple's promos. 

Pull request from feature branch to master branch. Thanks for any feedback!

### CODE REVIEW

**Comment by lekegitrepo** [comment]
This PR is under Review by **_[TSE] Temitayo Adeleke_**

**Comment by lekegitrepo** [comment]
### Hi @Maclenn77,
**Good job so far**  👏 but you still need to make some changes to improve the page and your project.

1. You need to improve your pull request summary, it should include what did in the project.
As mentioned in the project requirement: Pull Request should have a meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).

2. The navigation bar isn't as beautiful as the one you have in your readme file try to fix this.

**_This is the one from your readme file:_**

image

**_This is the from your page:_**

image

3. The background image is not aligned with the bottom image. Check the images below:

**_This is the original:_**

image

**_This is your version:_**

review-image

* Try to align the image and handle the horizontal scroll bar(it should not have horizontal scroll).
**_Kindly fix these and resubmit for review_**

if you have any doubt or question you can contact me on slack.

### Reviewed by: Temitayo Adeleke

-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Require Changes

**Comment by Maclenn77** [comment]
### Hi @lekegitrepo,

Thanks for the feedback. I fixed the problems and resubmited for review.

Have a good day.

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi @Maclenn77, there is still a problem with your page :fast_forward:**

1. There should be no whitespaces to the top, left, and right of the main content as you have in your page. It should cover 100% of the page width.

apple

2. Your footer is no more well aligned. Kindly check it.

image

3. Remove the install, usage, test and deployment sections in your README since they may not be relevant for this project.

4. Optional: consider adding a live link to your README. You can generate one [here](https://raw.githack.com)

_**Kindly make these changes and submit another code review request.**_

**Any question? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes required.

**Comment by Maclenn77** [comment]
**All changes proposed by @mosesogwo has been done.** 

Thanks for the feedback!

**Review by MarioDena — APPROVED** [review]
Hello my name is Mario! Congratulations on your project and on making the requested changes.

I would recommend a few optional changes:

## Optional Changes:

- [x] There is no search icon on your search bar, you could improve that. __This change is [Optional]__

- [x] There are a few repeated rules on your CSS, if you haven't reach the article about good coding practices I would recommend revisiting your code one you do.  __This change is [Optional]__


## This project is aproved ❕ 🎖 🏅  Congratulations!


## Code review by Mario Enrique Delgado Naranjo

**Comment by Maclenn77** [comment]
Thanks, @MarioDena . Checked repetitive code in CSS and I'll merge right now!

**Comment by Maclenn77** [comment]
Merging to Master.

**Pull request merged**
